### ISSUE TITLE
ACL Roles does not work correctly

### ISSUE THREAD

**Issue by arthurlm** [FriendsOfSymfony/FOSCommentBundle#156]
Hi all !

FOS Comment Bundle works corectly on my website, but there is a problem with ACL roles.
Indeed, I can't delete or edit comment if I am connected as administrator ...
Moreover if I am not connected, I always can see comment ...

My config.yml file contains :

``` yaml
fos_comment:
    db_driver: orm
    class:
        model:
            comment:    Mediterranee\HomeBundle\Entity\Comment
            thread:     Mediterranee\HomeBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
```

Anyone could help me ?
