### ISSUE TITLE
Redirection after posting a new comment

### ISSUE THREAD

**Issue by alphaql** [FriendsOfSymfony/FOSCommentBundle#185]
Redirecting after post a comment

Hi. When I try to add a comment, after pressing the submit button, the page is redirected to a page like this:

http://mypage.loc/app_dev.php/api/threads/22/comments/19

On this page, I can see my comment  and  few buttons (Send, edit, etc. ..)

After reading several similar issues, I thought in to add these lines in config.yml file but the problem continues:

``` yaml
fos_rest:
     view:
         formats:
             rss: true
             xml: false
         templating_formats:
             html: true
         force_redirects:
             html: true
         failed_validation: HTTP_BAD_REQUEST
         default_engine: twig
         view_response_listener: true
```

In my file twig, I have the following:

``` html+jinja
     {# ------------------------------------------------ -------------------------------- #}

     {% Block comment%}

     <div id="fos_comment_thread" data-thread="{{ thread.id }}"> </ div>
     {% Include 'FOSCommentBundle: Thread: comments.html.twig' with {'comments': comments, 'thread': thread}%}
     {% Endblock%} comment
     Javascript {% block%}
         {% Javascripts '@ FOSCommentBundle / Resources / assets / js / comments.js'%}
             <script type="text/javascript" src="{{ asset_url }}">
                 / / URI identifier for the thread comments
                 fos_comment_thread_id var = "{{path ('fos_comment_get_thread_comments', {' id ': thread.id})}}';
             </ script>
         Endjavascripts%} {%
     Javascript {% endblock%}
     {# ------------------------------------------------ -------------------------------- #}
```

According to the firebug, I have no javascript errors. If I refresh the original page, I can see the new comment.

I don't know where is the problem. :S

Thanks in advance.
