### ISSUE TITLE
[master]Problem with acl

### ISSUE THREAD

**Issue by n1c01a5** [FriendsOfSymfony/FOSCommentBundle#204]
I would that only User ( or an admin) who creates the comment can it modify. I followed the step 7-8 in documentation about acl and so I add acl in my config but it does not works.

My config.yml:

``` yaml
# FOSCommentBundle
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\CommentBundle\Entity\Comment
            thread: Application\CommentBundle\Entity\Thread
    acl: true
    service:
        manager:
            thread: fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote: fos_comment.manager.vote.acl
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_USER
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
```

The author of the comment is identified but he can modify all the comments.

Any idea?
