### ISSUE TITLE
Problem to change the service fos_comment.acl.thread.security

### ISSUE THREAD

**Issue by n1c01a5** [FriendsOfSymfony/FOSCommentBundle#244]
I follow this instructions #243.

config.yml:

```
# FOSCommentBundle
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\CommentBundle\Entity\Comment
            thread: Application\CommentBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread: application_comment.acl.thread.security
            comment: application_comment.acl.comment.security
```

My Application\CommentBundle\DependencyInjection\ApplicationCommentExtension.php

```
<?php

namespace Application\CommentBundle\DependencyInjection;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;
use Symfony\Component\DependencyInjection\Loader;

/**
 * This is the class that loads and manages your bundle configuration
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/extension.html}
 */
class ApplicationCommentExtension extends Extension
{
    /**
     * {@inheritDoc}
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('acl.yml');
    }
}
```

My Application\CommentBundle\Resources\config\acl.yml

```
services:
    application_comment.acl.thread.security:
        class: Application\CommentBundle\Acl\SecurityThreadAcl
        arguments: [@security.context, @security.acl.object_identity_retrieval_strategy, @security.acl.provider]
    application_comment.acl.comment.security:
        class: Application\CommentBundle\Acl\SecurityCommentAcl
        arguments: [@security.context, @security.acl.object_identity_retrieval_strategy, @security.acl.provider]
```

My Application\CommentBundle\Acl\SecurityThreadAcl.php

```
<?php

namespace Application\CommentBundle\Acl;

use FOS\CommentBundle\Acl\SecurityThreadAcl as BaseSecurityThreadAcl;
use Symfony\Component\Security\Acl\Model\AclInterface;
use Symfony\Component\Security\Acl\Permission\MaskBuilder;

class SecurityThreadAcl extends BaseSecurityThreadAcl
{
    protected function doInstallFallbackAcl(AclInterface $acl, MaskBuilder $builder)
    {
        $builder->add('iddqd');
        $acl->insertClassAce(new RoleSecurityIdentity('ROLE_SUPER_ADMIN'), $builder->get());

        $builder->reset();
        $acl->insertClassAce(new RoleSecurityIdentity('IS_AUTHENTICATED_ANONYMOUSLY'), $builder->get());

        $builder->reset();
        $builder->add('create');
        $builder->add('view');
        $acl->insertClassAce(new RoleSecurityIdentity('ROLE_USER'), $builder->get());
    }
}
```

My Application\CommentBundle\Acl\SecurityCommentAcl.php

```
<?php

namespace Application\CommentBundle\Acl;

use FOS\CommentBundle\Acl\SecurityCommentAcl as BaseSecurityCommentAcl;
use Symfony\Component\Security\Acl\Model\AclInterface;
use Symfony\Component\Security\Acl\Permission\MaskBuilder;

class SecurityCommentAcl extends BaseSecurityCommentAcl
{
    protected function doInstallFallbackAcl(AclInterface $acl, MaskBuilder $builder)
    {
        $builder->add('iddqd');
        $acl->insertClassAce(new RoleSecurityIdentity('ROLE_SUPER_ADMIN'), $builder->get());

        $builder->reset();
        $acl->insertClassAce(new RoleSecurityIdentity('IS_AUTHENTICATED_ANONYMOUSLY'), $builder->get());

        $builder->reset();
        $builder->add('create');
        $builder->add('view');
        $acl->insertClassAce(new RoleSecurityIdentity('ROLE_USER'), $builder->get());
    }
}
```

I have this error:

Warning: Missing argument 4 for FOS\CommentBundle\Acl\SecurityCommentAcl::__construct(), called in /var/www/Capeps/app/cache/dev/appDevDebugProjectContainer.php on line 61 and defined in /var/www/Capeps/vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle/Acl/SecurityCommentAcl.php line 80

Thanks for your help
