### ISSUE TITLE
Cannot load resource "@FOSCommentBundle/Resources/config/routing.yml"

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSCommentBundle#257]
I get the following error:
Cannot load resource "@FOSCommentBundle/Resources/config/routing.yml". Make sure the "FOSCommentBundle" bundle is correctly registered and loaded in the application kernel class. 

I have symfony 2.1.3-dev, my appKernel I have: "friendsofsymfony/comment-bundle" : "2.0.x",

My config.yml:

``` yaml
fos_comment:
   db_driver: orm
   class:
      model:
         comment: project\projectBundle\Entity\Comment
         thread: project\projectBundle\Entity\Thread
         vote: project\projectBundle\Entity\Vote
   acl: true
   acl_roles:
           comment:
               create: ROLE_USER
               view: IS_AUTHENTICATED_ANONYMOUSLY
               edit: ROLE_ADMIN
               delete: ROLE_ADMIN
           thread:
               create: IS_AUTHENTICATED_ANONYMOUSLY
               view: IS_AUTHENTICATED_ANONYMOUSLY
               edit: ROLE_ADMIN
               delete: ROLE_ADMIN
           vote:
               create: IS_AUTHENTICATED_ANONYMOUSLY
               view: IS_AUTHENTICATED_ANONYMOUSLY
               edit: ROLE_ADMIN
               delete: ROLE_ADMIN
   service:
       acl:
           thread: fos_comment.acl.thread.roles
           comment: fos_comment.acl.comment.roles
           vote: fos_comment.acl.vote.roles
```

My routing.yml:

``` yaml
fos_comment_api:
   type: rest
   resource: "@FOSCommentBundle/Resources/config/routing.yml"
   prefix: /api
```

And the FOSCommentBundle is in the directory: 
Vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle

Someone can I help me ?? I don`t understand why " Cannot load resource "@FOSCommentBundle/Resources/config/routing.yml". "
