### ISSUE TITLE
ACL Roles and CommentBundle configuration issue

### ISSUE THREAD

**Issue by helios-ag** [FriendsOfSymfony/FOSCommentBundle#33]
Well guys i have a strange behavior of CommentBundle settings defined through config.yml:
Here some example:
1. Works fine:

``` yaml

fos_comment:
    db_driver: orm
    class:
        model:
            comment: FM\UserBundle\Entity\Comment    
    form:
        comment:
            name: fos_comment_comment
            type: fos_comment.comment  
    service:
        acl:
            roles:
              comment:
                 create: IS_AUTHENTICATED_ANONYMOUSLY
                 view: IS_AUTHENTICATED_ANONYMOUSLY
                 edit: ROLE_ADMIN
                 delete: ROLE_ADMIN
              thread:
                 create: IS_AUTHENTICATED_ANONYMOUSLY
                 view: IS_AUTHENTICATED_ANONYMOUSLY
                 edit: ROLE_ADMIN
                 delete: ROLE_ADMIN
              vote:
                  create: IS_AUTHENTICATED_ANONYMOUSLY
                  view: IS_AUTHENTICATED_ANONYMOUSLY
                  edit: ROLE_ADMIN
                  delete: ROLE_ADMIN                 
        manager:
            thread: fos_comment.manager.thread.default
            comment: fos_comment.manager.comment.default
            vote: fos_comment.manager.vote.default
        acl:
            thread: fos_comment.acl.thread.security
            comment: fos_comment.acl.comment.security              
            vote: fos_comment.acl.vote.security
```
1. Not work, throw an exception (Unrecognized options "roles" under "fos_comment.service.acl"):

``` yaml

fos_comment:
    db_driver: orm
    class:
        model:
            comment: FM\UserBundle\Entity\Comment    
    form:
        comment:
            name: fos_comment_comment
            type: fos_comment.comment  
    service:           
        manager:
            thread: fos_comment.manager.thread.default
            comment: fos_comment.manager.comment.default
            vote: fos_comment.manager.vote.default
        acl:
            thread: fos_comment.acl.thread.security
            comment: fos_comment.acl.comment.security              
            vote: fos_comment.acl.vote.security
            roles:
              comment:
                 create: IS_AUTHENTICATED_ANONYMOUSLY
                 view: IS_AUTHENTICATED_ANONYMOUSLY
                 edit: ROLE_ADMIN
                 delete: ROLE_ADMIN
              thread:
                 create: IS_AUTHENTICATED_ANONYMOUSLY
                 view: IS_AUTHENTICATED_ANONYMOUSLY
                 edit: ROLE_ADMIN
                 delete: ROLE_ADMIN
              vote:
                  create: IS_AUTHENTICATED_ANONYMOUSLY
                  view: IS_AUTHENTICATED_ANONYMOUSLY
                  edit: ROLE_ADMIN
                  delete: ROLE_ADMIN     
```
1. Same behav as second example, but this described in docs(exception Unrecognized options "roles" under "fos_comment.acl"):

``` yaml

fos_comment:
    db_driver: orm
    class:
        model:
            comment: FM\UserBundle\Entity\Comment    
    form:
        comment:
            name: fos_comment_comment
            type: fos_comment.comment  
    service:           
        manager:
            thread: fos_comment.manager.thread.default
            comment: fos_comment.manager.comment.default
            vote: fos_comment.manager.vote.default
        acl:
            thread: fos_comment.acl.thread.security
            comment: fos_comment.acl.comment.security              
            vote: fos_comment.acl.vote.security
    acl:
        roles: # optional configuration for the Role Acl providers.
            comment:
                create: IS_AUTHENTICATED_ANONYMOUSLY
                view: IS_AUTHENTICATED_ANONYMOUSLY
                edit: ROLE_ADMIN
                delete: ROLE_ADMIN
            thread:
                create: IS_AUTHENTICATED_ANONYMOUSLY
                view: IS_AUTHENTICATED_ANONYMOUSLY
                edit: ROLE_ADMIN
                delete: ROLE_ADMIN
            vote:
                create: IS_AUTHENTICATED_ANONYMOUSLY
                view: IS_AUTHENTICATED_ANONYMOUSLY
                edit: ROLE_ADMIN
                delete: ROLE_ADMIN     
```
