### ISSUE TITLE
FOSCommentBundle in YAML

### ISSUE THREAD

**Issue by oldmill1** [FriendsOfSymfony/FOSCommentBundle#425]
What are the YAML implementation of Thread and Comment. Here's what I have: 

Thread.orm.yml
```
Johnson\BlogBundle\Entity\Thread:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
```
Comment.orm.yml
```
Johnson\BlogBundle\Entity\Comment:
    type: entity
    manyToOne:
        thread:
            targetEntity: Johnson\BlogBundle\Entity\Thread
            inversedBy: comments
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
```

I don't know what to do about the 

```
/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
```

Main Problem: 
------------------

Everytime I refresh the page the comments are on, the refresh action creates a new record in the Thread table (????) so that I have duplicate records with the same slug, and NULL for "last_comment_at". (See image)

![screen shot 2014-03-24 at 10 19 28 am](https://f.cloud.github.com/assets/384512/2500123/55d1da92-b35f-11e3-8f7a-29f06daf47e3.png)
