### ISSUE TITLE
Comment Sorting

### ISSUE THREAD

**Issue by jspizziri** [FriendsOfSymfony/FOSCommentBundle#436]
I've looked all around the interwebs, but I can't figure out how to change the sorting of the comments to be ascending. I can't find any documentation about it anywhere.

How can I make the comments sort ascending instead of descending?

I've tried the following:

```
fos_comment:
  service:
    sorting:
      default: (ASC sorting service)
```

but I keep getting a "Maximum function nesting level"(which is set at 200) error.

I've asked this same question in stack overflow here:
http://stackoverflow.com/questions/24067994/foscommentbundle-sorting
