### ISSUE TITLE
Roles : login form

### ISSUE THREAD

**Issue by hisem** [FriendsOfSymfony/FOSCommentBundle#48]
Hi,

Since I don't know where to look for help on this (really sweet) bundle, I'm creating an Issue, I hope you won't mind.

I'm trying to implement comments on my blog using Roles.

I would like users to be logged in (=ROLE_USER) to create a comment.

In my config, I did the following:

``` yaml
acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
```

If I'm logged in, everything works perfectly.

However, if I'm anonymous, here's what happens:
- Comment form is visible : I write my message
- I submit my message
- My form login appears in place of my thread (btw duplicating my layout -> that maybe my own fault)
- I log in
- I fall on the following exception : No route found for "GET /new/3": Method Not Allowed (Allow: POST) 

Is there something I'm doing wrong?

Many thanks, keep up the great work :-)

Rémi
