### ISSUE TITLE
[DOCUMENTATION] Issue on tag name for custom sorter

### ISSUE THREAD

**Issue by jmaquet** [FriendsOfSymfony/FOSCommentBundle#484]
I think that there is a typo issue in the documentation : 
https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/14-customizing_tree_sorting.md
At the end of the actual doc :
```
services:
    acme_comment.sorter.my_sort:
        class: Acme\CommentBundle\Sorting\AcmeOrderSorting
        tags:
            - { name: acme_comment.sorter, alias: my_sort }
```
I think the last line should be : 
```
            - { name: fos_comment.sorter, alias: my_sort }
```
