### ISSUE TITLE
Custom comment sorting

### ISSUE THREAD

**Issue by rajendradbpb** [FriendsOfSymfony/FOSCommentBundle#491]
Hi , 
    I need to implement the custom comment sorting based on the comment score , i have gone throgh this [14-customizing_tree_sorting.md](https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/14-customizing_tree_sorting.md) , but here i put  the "  services:  " in my app/config.yml  as follows

where i created the custom sorting class `CommentOrderSorting.php` under path `src/DemoBundle/Bundle/Sorting/ ` and my `config.yml `file looks as follows

```
# app/config/config.yml
services:
     demoBundle.comment.sorter.score:
        class: DemoBundle\Bundle\Sorting\CommentOrderSorting
        tags:
            - { name: fos_comment.sorter, alias: score }
```
Here the overridden methods of `SortingInterface` are not being called where i need to implement my logic

Thanks

**Comment by rajendradbpb** [comment]
Well  , I am sorry it was my fault that i did not configure correctly all I need to do is add the following lines

```
# app/config/config.yml
fos_comment:
    service:
        sorting:
            default: score
```
