### ISSUE TITLE
login form when there is no comment and you're not connected

### ISSUE THREAD

**Issue by paul-mesnilgrente** [FriendsOfSymfony/FOSCommentBundle#511]
Hello,

my configuration is like that:
```
# app/Ressources/config/config.yml
fos_comment:
    db_driver: orm
    class:
        model:
            comment: AppBundle\Entity\Comment
            thread: AppBundle\Entity\Thread
            vote: AppBundle\Entity\Vote
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
```

my display :
```twig
{% include 'FOSCommentBundle:Thread:async.html.twig' with {'id': post.id} %}
```

As you can see, when you're not connected, you can watch comment but not add. There is no problem after the first comment. But when there is no comment, the login form appear a the place of the comment and it makes some display bugs.

Is it possible to retire this login form ?
