### ISSUE TITLE
Compatible with easyadmin

### ISSUE THREAD

**Issue by krysennn** [FriendsOfSymfony/FOSCommentBundle#531]
Hi, i use FOSCommentBundle in my project and i use EasyAdmin on SF2.

Your method "isCommentable" in Model\Thread.php is not modify with easyadmin....

config.yml for easyadmin:
My Class Article is extend of BaseThread
```
Article: 
            class: AppBundle\Entity\Article
            list: 
                fields:
                    - { property: 'id' } 
                    - { property: 'isCommentable'}
```
EasyAdmin return this error:

> Neither the property "isCommentable" nor one of the methods "addIsCommentable()"/"removeIsCommentable()", "setIsCommentable()", "isCommentable()", "__set()" or "__call()" exist and have public access in class "AppBundle\Entity\Article".

The problem:
line 58 in Model\ThreadInterface.php (replace setCommentable with setisCommentable)
line 105 in Model\Thread.php (replace setCommentable with setisCommentable)

Do you have solution to bypass this error or override these model ?

Thank you
Best regards,
Alexis.
