### ISSUE TITLE
I have an exception including the comment template "Neither the property "note"

### ISSUE THREAD

**Issue by aimeric** [FriendsOfSymfony/FOSCommentBundle#558]
Hi,

I'm trying to include `comments.html.twig` in my page index, but i have this error:

`An exception has been thrown during the rendering of a template ("Neither the property "note" nor one of the methods "getNote()", "note()", "isNote()", "hasNote()", "__get()" exist and have public access in class "Application\Sonata\CommentBundle\Entity\Comment".") in FOSCommentBundle:Thread:comments.html.twig at line 17.`

Is my first time using this bundle, i'm a bit lost .

This what i have put inside of **index.html.twig**

```
     <script src="http://code.jquery.com/jquery-1.11.3.js"></script>
                    <div id="fos_comment_thread" data-thread="{{ thread.id }}">

                        {% include 'FOSCommentBundle:Thread:comments.html.twig' with {
                        'comments': comments,
                        'thread': thread
                        } %}
```

**controller:**

 ```
public function indexvAction($quantityLimit, Request $request)
    {
      
        $session = $this->getRequest()->getSession();
        $em = $this->getDoctrine()->getManager();
        $findEntities = $em->getRepository('FLYBookingsBundle:Post')->product($quantityLimit);
        $entity = $this->get('knp_paginator')->paginate($findEntities, $this->get('request')->query->get('page', 1), 9
        );

        $id = 'thread_id';
        $thread = $this->container->get('fos_comment.manager.thread')->findThreadById($id);
        if (null === $thread) {
            $thread = $this->container->get('fos_comment.manager.thread')->createThread();
            $thread->setId($id);
            $thread->setPermalink($request->getUri());

            // Add the thread
            $this->container->get('fos_comment.manager.thread')->saveThread($thread);
        }
        $comments = $this->container->get('fos_comment.manager.comment')->findCommentTreeByThread($thread);
        if ($session->has('cart'))
            $cart = $session->get('cart');
        else
            $cart = false;
        return $this->render('FLYBookingsBundle:Post:indexv.html.twig', array('quantityLimit' => $quantityLimit,'entity' => $entity,
            'cart' => $cart,'comments' => $comments,
            'thread' => $thread,));


    }
```

**config.yml**

```
sonata_comment:
    manager_type: orm # can be 'orm' or 'mongodb'
    class:
        comment: Application\Sonata\CommentBundle\Entity\Comment # This is an optional value
        thread:  Application\Sonata\CommentBundle\Entity\Thread   # This is an optional value

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\Sonata\CommentBundle\Entity\Comment
            thread: Application\Sonata\CommentBundle\Entity\Thread
    form:
        comment:
            type: sonata_comment_comment
```

entity **comment.php**

```
<?php


namespace Application\Sonata\CommentBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Comment as BaseComment;
use FOS\CommentBundle\Model\SignedCommentInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Application\Sonata\UserBundle\Entity\User;
/**
 * @ORM\Entity
 */
class Comment extends BaseComment implements SignedCommentInterface
{
    // .. fields

    /**
     * Author of the comment
     *
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
     * @var User
     */
    protected $author;

    public function setAuthor(UserInterface $author)
    {
        $this->author = $author;
    }

    public function getAuthor()
    {
        return $this->author;
    }

    public function getAuthorName()
    {
        if (null === $this->getAuthor()) {
            return 'Anonymous';
        }

        return $this->getAuthor()->getUsername();
    }
}
```

**thread.php**

```
<?php



namespace Application\Sonata\CommentBundle\Entity;

use Sonata\CommentBundle\Entity\BaseThread as BaseThread;


class Thread extends BaseThread
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
}
```

routing.yml

```
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
```
