### ISSUE TITLE
Managing many threads / comments in config

### ISSUE THREAD

**Issue by Aximem** [FriendsOfSymfony/FOSCommentBundle#567]
I use FOSCommentBundle in my project, I already configured it with a thread and a comment class and this is working. But now I need to manage many types of thread and comment.

For example I have News with comments and I have Contents with comments. Of course, the news comments are different from content comments.

I don't know how to do it in the config.yml :

```
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Project\MyBundle\Entity\Comment
            thread: Project\MyBundle\Entity\News
```
How can I add my other thread / comment type ? Or how can I manage this case ?

TY
