### ISSUE TITLE
REST Api connecting to FOSCommentBundle async.html.twig, I'm getting response in network but norhing is in the DOM

### ISSUE THREAD

**Issue by developerrajtomar** [FriendsOfSymfony/FOSCommentBundle#595]
Hi Team,
I'm using **FOSCommentBundle** bundle and trying to integrate commenting through **JavaScript and JSON REST Api's**, The **async.html.twig** is sending a request to fetch the comments from the database and Also response in the network console I'm able to see, but when come's to frontend I cannot see anything in the UI, also, when I'm trying to **HOOK various JS Hook** i'm able to alert on those hooks but **none of them contains the actual data object**, I've tried to **log the things and debugger in chrome**, but still I didn't able to find a logic.

Anyone can help me out with it, because **I don't know is it a bug or there is a problem with my code**. I'm attaching my code snippet here:

> $(document)
    .on('fos_comment_show_form', '.fos_comment_comment_reply_show_form', function (event, data) {
      alert(data);
    })
    .on('fos_comment_load_thread', function (e, d) {
      console.log(window.fos.Comment.thread_container.html());
      console.log($('#fos_comment_thread').text());
      console.log(e, d);
    })

similarly all the hooks and 
![desctop screenshot](https://cloud.githubusercontent.com/assets/6761466/23903579/ff7cada4-08ea-11e7-9a0f-9d05cc431671.png)

**Comment by psyray** [comment]
I have the same problem, and the solution was in the FOS REST config.
Check that your api/threads URL returns HTML and not JSON
```
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api/threads', priorities: ['html'], fallback_format: 'html' }
            - { path: '^/api/', priorities: ['json'], fallback_format: 'json' }
```
