### ISSUE TITLE
Symfony 4.3 - The child node "db_driver" at path "fos_comment" must be configured.

### ISSUE THREAD

**Issue by z0om** [FriendsOfSymfony/FOSCommentBundle#698]
Hello,

I followed your documentation but I have this issue 'The child node "db_driver" at path "fos_comment" must be configured.'

![image](https://user-images.githubusercontent.com/5561613/68381884-e50cf880-0152-11ea-92c7-868a0b8867eb.png)

What I did.

➡ config/config.yaml

```
framework:
    http_method_override: true
    translator: ~

fos_comment:
    db_driver: orm
    class:
        model:
            comment: App\Entity\Comment
            thread: App\Entity\Thread

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

assetic:
    bundles: [ "FOSCommentBundle" ]   
```

➡ src/Entity.php

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Comment as BaseComment;

/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Comment extends BaseComment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Thread of this comment
     *
     * @var Thread
     * @ORM\ManyToOne(targetEntity="App\Entity\Thread")
     */
    protected $thread;
}
```
➡ src/Thread.php

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Thread as BaseThread;

/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Thread extends BaseThread
{
    /**
     * @var string $id
     *
     * @ORM\Id
     * @ORM\Column(type="string")
     */
    protected $id;
}
```

➡ templates/index.html.twig

I inserted this part :
`{% include '@FOSComment/Thread/async.html.twig' with {'id': 'foo'} %}`

Nothing else, neither make:migration...

Thank for helping
